ipython3 index_gen.py
ipython3 research_page_gen.py
ipython3 people_page_gen.py
ipython3 publications_page_gen.py
ipython3 publications_compact_page_gen.py
ipython3 teaching_page_gen.py
ipython3 news_page_gen.py
ipython3 contact_page_gen.py